sequenceDiagram
    title Diagramme de Séquence
	participant Utilisateur
	participant Système as S
	participant BaseDeDonnées as DB
	Utilisateur->>Système: Requête de données
	Système->>BaseDeDonnées: Interroger la DB
	BaseDeDonnées-->>Système: Données renvoyées
	Système-->>Utilisateur: Afficher les résultats
