sequenceDiagram
    participant AS as AgentSupervisor
    participant CM as ConfigManager
    participant RC as ResourceController
    participant CA as ConnectivityAsync
    participant AM as AWSManager
    participant DM as DockerManager
    participant VM as VectorManager
    participant SM as SuricataManager
    participant MS as MetricsServer
    participant GW as GitWorkflow
    participant SRM as SuricataRulesManager
    participant WIM as WebInterfaceManager
    database SS as SharedState

    AS->>CM: Init
    AS->>DM: Init
    AS->>VM: Init
    AS->>SM: Init
    AS->>GW: Init

    AS->>GW: CheckBranch
    AS->>VM: GenerateVectorConfig
    AS->>SM: GenerateSuricataConfig
    AS->>SM: StartSuricata

    AS->>DM: PrepareDockerStack

    AS->>RC: StartResourceController
    RC->>SS: UpdateCpuUsage
    RC->>SS: UpdateRamUsage
    RC->>SS: UpdateThrottlingLevel

    AS->>MS: StartMetricsServer
    MS->>SS: GetCpuUsage
    MS->>SS: GetRamUsage
    MS->>SS: GetRedisQueueDepth
    MS->>SS: GetVectorHealthy
    MS->>SS: GetIngestionRateIncrement
    MS->>SS: GetErrorIncrement
    MS->>SS: GetAwsReady
    MS->>SS: GetRedisReady
    MS->>SS: GetPipelineOk
    MS->>SS: GetThrottlingLevel
    MS->>SS: ResetIngestionRateIncrement
    MS->>SS: ResetErrorIncrement

    AS->>SRM: StartSuricataRulesManager
    SRM->>SS: LogError

    AS->>WIM: StartWebInterfaceManager

    AS->>DM: CheckStackHealth
    DM->>SS: UpdateDockerHealthy

    AS->>CA: StartConnectivityAsync
    CA->>AM: InitAwsManager
    CA->>AM: GetOpenSearchClient
    CA->>SS: UpdateAwsReady
    CA->>SS: UpdateRedisReady
    CA->>SS: UpdatePipelineOk
    CA->>SS: LogError

    AS->>SS: GetAwsReady
    AS->>SS: UpdatePipelineOk

    AS->>AS: MonitorProcesses
    AS->>AS: GracefulShutdown
    AS->>DM: StopDockerStack
