from typing import Protocol, AsyncGenerator
from src.ids.domain.entities import AlerteIDS # Import mis à jour

class AlerteSource(Protocol):
    """Interface pour une source d'alertes IDS."""
    async def fournir_alertes(self) -> AsyncGenerator[AlerteIDS, None]: ...
    async def valider_connexion(self) -> bool: ...
    async def arreter(self) -> None: ...
