from typing import Protocol, Any

class GestionnaireConfig(Protocol):
    """Interface pour la gestion de configuration."""
    def obtenir(self, clé: str, defaut: Any = None) -> Any: ...
    def definir(self, clé: str, valeur: Any) -> None: ...
    def recharger(self) -> None: ...
